version: '3.7'

services:

  fronttest:
    container_name: FrontTest_23_1
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '14444:44486'
    environment:
      - CHOKIDAR_USEPOLLING=true