name: "OMMAT CiCd"
on:
  push:
    branches: ["Test"]
    
jobs:
  deploy:
    name: Deploy Front Test
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
            ${{ secrets.SECRET_COMMAND }};
            ${{ secrets.SECRET_COMMAND_TWO }}
            cd ${{ secrets.PROJECT_FOLDER }};
            git checkout Test;
            git pull;
